# Generated by Django 6.0.1 on 2026-05-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='drink_type',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='is_alcoholic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='tip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
