# Generated by Django 6.0.1 on 2026-05-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_beveragecategory_cocktail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='category',
        ),
    ]
